subscriber_topic: "/ouster/points"
status_subscriber_topic: "/rbd_status"
collision_service: "/collision"
flagged_pointcloud: "/output_PC2_flagged"
scan_pointcloud: "/output_PC2_scan"
critical_dist_back: 550
critical_dist_left: 330
critical_dist_front: 700
critical_dist_right: 330
lim_rows_back: 2