# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/juri/git/rbd_packages/rbd_local/zhaw_ba_robodog/ui/control_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 604)
        Dialog.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 100, 166, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 701))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 90, 701, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.activateButton = QtWidgets.QPushButton(self.widget)
        self.activateButton.setGeometry(QtCore.QRect(198, 200, 141, 31))
        self.activateButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(124, 191, 126);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.activateButton.setObjectName("activateButton")
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setGeometry(QtCore.QRect(30, 550, 141, 31))
        self.exitButton.setStyleSheet("border-radius: 10px;\n"
"border: 0.5px solid white;\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.exitButton.setObjectName("exitButton")
        self.stopButton = QtWidgets.QPushButton(self.widget)
        self.stopButton.setGeometry(QtCore.QRect(198, 250, 141, 31))
        self.stopButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 149, 149);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.stopButton.setObjectName("stopButton")
        self.recognitionLabel = QtWidgets.QLabel(self.widget)
        self.recognitionLabel.setGeometry(QtCore.QRect(0, 140, 701, 51))
        self.recognitionLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.recognitionLabel.setScaledContents(True)
        self.recognitionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recognitionLabel.setObjectName("recognitionLabel")
        self.sitButton = QtWidgets.QPushButton(self.widget)
        self.sitButton.setGeometry(QtCore.QRect(359, 250, 141, 31))
        self.sitButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(254, 182, 56);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.sitButton.setObjectName("sitButton")
        self.standButton = QtWidgets.QPushButton(self.widget)
        self.standButton.setGeometry(QtCore.QRect(359, 200, 141, 31))
        self.standButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(170, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.standButton.setObjectName("standButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(320, 310, 61, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(110, 360, 61, 16))
        self.label_3.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(250, 360, 81, 16))
        self.label_4.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(530, 360, 51, 16))
        self.label_6.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(390, 360, 51, 16))
        self.label_5.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(210, 400, 141, 121))
        self.label_13.setStyleSheet("image: url(:/newPrefix/hand_updown.jpg);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(70, 400, 141, 121))
        self.label_14.setStyleSheet("image: url(:/newPrefix/hand_wave.jpg);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(350, 400, 141, 121))
        self.label_15.setStyleSheet("image: url(:/newPrefix/hand_walk.jpg);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(490, 400, 141, 121))
        self.label_16.setStyleSheet("image: url(:/newPrefix/hand_spin.jpg);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Controls"))
        self.activateButton.setText(_translate("Dialog", "Activate Recognition"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
        self.stopButton.setText(_translate("Dialog", "Stop Recognition"))
        self.recognitionLabel.setText(_translate("Dialog", "Gesture Recognition: off"))
        self.sitButton.setText(_translate("Dialog", "Sit"))
        self.standButton.setText(_translate("Dialog", "Stand"))
        self.label_2.setText(_translate("Dialog", "Gestures:"))
        self.label_3.setText(_translate("Dialog", "1. Wiggle"))
        self.label_4.setText(_translate("Dialog", "2. Bounce"))
        self.label_6.setText(_translate("Dialog", "4. Spin"))
        self.label_5.setText(_translate("Dialog", "3. Walk"))
import res_rc
