# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/juri/git/rbd_packages/rbd_local/zhaw_ba_robodog/ui/start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 604)
        Dialog.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 100, 166, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 701))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 90, 701, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 255); \n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.connectButton = QtWidgets.QPushButton(self.widget)
        self.connectButton.setGeometry(QtCore.QRect(280, 200, 141, 31))
        self.connectButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(124, 191, 126);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.connectButton.setObjectName("connectButton")
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setGeometry(QtCore.QRect(40, 540, 141, 31))
        self.exitButton.setStyleSheet("border-radius: 10px;\n"
"border: 0.5px solid white;\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.exitButton.setObjectName("exitButton")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(0, 230, 701, 51))
        self.errorLabel.setStyleSheet("color: rgb(255, 38, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.errorLabel.setText("")
        self.errorLabel.setScaledContents(True)
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Gesture Recognition with A1 Robot"))
        self.connectButton.setText(_translate("Dialog", "Connect to Robot"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
